### ISSUE TITLE
Issue: 잘못된 어노테이션 사용

### ISSUE THREAD

**Issue by mukhoplus** [GoLAB-Project/GoLAB-backend#7]
## Issue: Use incorrect annotation
잘못된 어노테이션 사용

## Description
user_id에 @GeneratedValue(strategy = GenerationType.IDENTITY) 어노테이션이 붙어있음

## Bug
- [x] GamerRecord
- [x] User

**Comment by skybluelion** [comment]
잘 몰라서 그랬습니다 ㅜ
